import random

LEVEL_1_TEMPLATES = [
    "Babe, {task}. By {deadline}. I believe in you. Barely, but I do 🙃",
    "Not to be dramatic but {task} has been staring at me from the to-do list. It's judging us both. {deadline} 👀",
    "Hey so {task} — you gonna do it or should I start a countdown? Deadline: {deadline} ⏰",
    "Cute that you think I forgot about {task}. I didn't. {deadline}. Chop chop 💅",
    "Sooo {task} is still a thing that needs doing. By {deadline}. In case your memory needs a hug 🤗",
    "Dropping this here: {task}. Deadline: {deadline}. Don't make me come back 😘",
    "Quick reminder that {task} won't manifest itself into completion. Trust me, I've tried. {deadline} ✨",
    "You know what would be really attractive? If you'd {task}. By {deadline}. Think about it 😏",
    "Gentle nudge from your favorite nag bot: {task}. {deadline} is the target. You got this 🎯",
    "Hi hello, just checking in on {task}. The deadline ({deadline}) is approaching with great enthusiasm 🚶‍♀️",
    "If {task} were a houseplant, it'd be looking thirsty rn. Deadline: {deadline} 🪴",
    "Knock knock. Who's there? {task}. Waiting for you. Until {deadline} 🚪",
    "Reminder #1, delivered with love and only mild passive aggression: {task} by {deadline} 💌",
    "Today on 'things that still need doing': {task}. By {deadline}. Tune in next time! 📺",
    "Hey rockstar, {task} is on the setlist. Showtime: {deadline} 🎤",
    "Polite ping: {task}. Deadline {deadline}. I won't ping politely again 🔔",
    "Future you will thank present you for finishing {task} before {deadline}. Just saying 🔮",
    "Pst. {task}. {deadline}. Pass it on 🤫",
    "Don't kill the messenger but {task} still needs handling by {deadline} 📬",
    "Light reminder for a heavy task: {task}. Due {deadline}. You're built for this 💪",
    "Just me, your bot, checking on {task}. Deadline {deadline}. Carry on ✌️",
    "If procrastination were an art, you'd be Picasso. But also {task}. By {deadline} 🎨",
    "Hey love, {task} is patiently waiting. {deadline} is the magic moment ⏳",
    "Casual reminder: the universe still expects {task} to happen by {deadline} 🌌",
    "Putting this on your radar (again, gently): {task} by {deadline} 📡",
    "Your scheduled wholesome reminder to {task} by {deadline}. Have a great day! 🌞",
    "{task} called. It misses you. It also has a deadline: {deadline} 📞",
    "Look at you, person who's about to {task} before {deadline}. So impressive 👏",
    "Soft launch: {task}. Full launch deadline: {deadline} 🚀",
    "I'd never pressure you but {task} is still happening, right? By {deadline}? 😇",
    "Tiny task, tiny reminder: {task}. {deadline} is when it's due 🐜",
    "Hey, the to-do list dragon is hissing about {task}. Tame it by {deadline} 🐉",
    "A friendly heads up that {task} continues to exist. Deadline {deadline} 🫣",
    "If I could do {task} for you, I would. I can't. Deadline {deadline} 🤖",
    "Setting the scene: there is a task. The task is {task}. The deadline is {deadline}. Curtain rises 🎭",
    "Whispering this so I don't startle you: {task}... by {deadline} 🌬️",
    "Pencil this in: {task}. Highlight it even. Deadline: {deadline} ✏️",
    "Reminder powered by good vibes only: {task} by {deadline} 🌈",
    "You haven't forgotten, right? About {task}? Due {deadline}? Right?? 🙂",
    "Just slid into your DMs to mention {task}. Deadline {deadline}. K bye 💁",
    "The vibes say {task} is about to get done before {deadline}. Manifest it 🔮",
    "Brief intermission to remind you: {task} by {deadline}. Back to your show 🎬",
    "Spoiler: future-you really wishes past-you had done {task} by {deadline} 📖",
    "{task} is like that browser tab you keep meaning to read. Deadline {deadline} 🔖",
    "Friendly fun fact: {task} is still on the list. Deadline {deadline} 🤓",
    "Operator standing by. {task} pending. Deadline {deadline}. Over 📻",
    "Drop everything (or schedule it): {task} by {deadline}. Or don't drop it. Just do the task 🫳",
    "Today's forecast: 100% chance of {task} happening by {deadline}. Hopefully 🌤️",
    "Insert reminder here: {task}. Insert deadline here: {deadline}. Insert action here: ??? 🧩",
    "End of polite reminder transmission. Subject: {task}. Deadline: {deadline} 📤",
]

LEVEL_2_TEMPLATES = [
    "Okay so I KNOW you saw my last message about {task}. The deadline is {deadline}. Don't play with me 🫠",
    "Me: please {task}. You: *pretends to not see*. The deadline: {deadline}. This relationship: struggling 💔",
    "I'm not saying I'm keeping score, but {task} has been pending since I first asked. {deadline} is RIGHT THERE 📋",
    "If I had a rupee for every time I reminded you to {task}, I'd have enough to hire someone else to do it. {deadline} 💸",
    "POV: you're {task} and you've been ghosted. Deadline {deadline} is feeling very neglected rn 👻",
    "The fact that {task} is still undone is giving 'I'll do it later' energy and later was {deadline} 😤",
    "Babe I love you but I will lose it if I have to remind you about {task} again. DEADLINE: {deadline} 🫡",
    "Just checked — {task} still not done. Also checked — my patience is running low. {deadline} btw 🙄",
    "Google search: how to make partner {task} before {deadline} without committing a crime 🔍",
    "You know the vibe when someone says 'I'll do it' and then doesn't? That's you with {task}. {deadline} 🎭",
    "Reminder two of three. {task}. {deadline}. Reminder three is going to be feral. Just FYI 🦝",
    "I'm starting to suspect {task} is being avoided on purpose. Bold strategy. Deadline {deadline} 🕵️",
    "Listen. I asked nicely. Now I'm asking with eye contact. {task}. {deadline} 👁️",
    "Your task ({task}) has now been pending long enough to qualify for a senior citizen discount. Deadline was {deadline} 👴",
    "If avoidance burned calories you'd be ripped by now. {task}. {deadline}. Less avoiding, more doing 💪",
    "I'm doing the deep breaths. In. Out. {task}. {deadline}. In. Out. Still annoyed 🧘",
    "We need to talk. About {task}. About {deadline}. About your relationship to to-do lists 🛋️",
    "The audacity of {task} being undone with {deadline} this close is sending me 💀",
    "I'm not mad. I'm disappointed. About {task}. Deadline {deadline}. Same difference tbh 😐",
    "Plot twist: the {task} doesn't do itself. Deadline still {deadline}. Wild 🌀",
    "If procrastination were an Olympic sport you'd at least be doing SOMETHING. {task}. {deadline} 🥱",
    "Asking again because clearly the first time was just decorative: {task}. {deadline}. ANSWER 📣",
    "I see you've opened Instagram 47 times today. Have you opened the {task} task? Deadline {deadline} 📱",
    "The fridge magnets are starting to talk about you. They want {task} done by {deadline} 🧲",
    "I'm typing this through gritted teeth. {task}. {deadline}. Please 🦷",
    "Round two. {task} still exists. {deadline} still looming. Ding ding 🥊",
    "I'd accept a partial effort at this point. Half-{task}, by {deadline}? Negotiating in good faith 🤝",
    "Things older than {task} being undone: nothing. {deadline} approaches 🕰️",
    "If you spent the time on {task} that you spent reading reminders about {task}, we'd be done. Deadline {deadline} 📚",
    "I'm going to start charging interest. {task}. Original deadline: {deadline}. Accruing rapidly 💰",
    "This is your bot speaking. Please {task} by {deadline}. Service may be interrupted otherwise 📢",
    "Updating my LinkedIn: 'World-class nagger about {task}.' Endorse my skills. Deadline {deadline} 💼",
    "I'm not yelling. I'm just typing in caps to emphasize the URGENCY of {task}. DEADLINE {deadline} 🔊",
    "Question: do you remember {task}? Because {deadline} sure does ❓",
    "I would have done {task} in the time it took to send these reminders. Deadline {deadline} ⏱️",
    "Manifestation isn't working. Time for action. {task}. {deadline} 🪄",
    "If {task} were a person, it'd be applying to other households for adoption. Deadline {deadline} 🏠",
    "Hello from your increasingly impatient bot. {task}. {deadline}. Please ✨",
    "I checked the task list. It checked me back. {task} still there. Deadline {deadline} 📋",
    "Look me in the eye and tell me {task} is happening by {deadline}. I'll wait 👀",
    "Apparently {task} requires divine intervention. Praying. Deadline {deadline} 🙏",
    "Drama level rising. {task}. {deadline}. The plot thickens 🎬",
    "On a scale of 1 to 10, how done is {task}? Spoiler: not 10. Deadline {deadline} 📊",
    "I will not be silenced. {task}. {deadline}. Spreading the word 📯",
    "Notification fatigue is real. Imagine how the {task} feels. Deadline {deadline} 🔔",
    "I'm sending this with a sigh you can practically hear. {task}. {deadline} 😮‍💨",
    "Behold: the second reminder. {task}. {deadline}. Third reminder unlocks chaos mode 🔓",
    "I'd offer to negotiate but {deadline} doesn't negotiate. {task}. Time's ticking ⏲️",
    "Two reminders in. Zero progress out. {task}. {deadline}. The math is bad 🧮",
    "Just so we're aligned: {task} hasn't been done. {deadline} hasn't moved. I'm losing it 🤯",
]

LEVEL_3_TEMPLATES = [
    "THIRD REMINDER. {task}. {deadline}. I am now emotionally identifying with that dripping faucet because I too am DRIPPING with frustration 🚰😤",
    "Okay I'm drafting two messages rn — one is a reminder to {task} (deadline: {deadline}), the other is to a divorce lawyer. Which one should I send? 💌",
    "I've asked about {task} more times than you've said 'I love you' this month. Deadline was {deadline}. Let that satisfying little fact sink in 📊",
    "Sir. SIR. {task}. The deadline was {deadline}. I have been more patient than a saint and I am NOT a saint 🔥",
    "Imagine explaining to our kids one day that mummy left because daddy wouldn't {task} by {deadline}. The legacy you're building rn is WILD 🏆",
    "Breaking news: Area person achieves the impossible — ignoring THREE reminders to {task}. Deadline {deadline} found dead in a ditch. Thoughts and prayers 📰💀",
    "If ignoring {task} was an Olympic sport, you'd have the gold, silver, AND bronze. Deadline was {deadline}. Standing ovation from absolutely no one 🥇🥈🥉",
    "I asked nicely. I asked firmly. Now I'm asking like someone who knows your mother's phone number and isn't afraid to use it. {task}. {deadline}. NOW 📞",
    "Fun game: what's older — the leftovers in the fridge or the reminder to {task}? Trick question. It's my resentment. {deadline} was AGES ago 🧊",
    "The {task} situation has now been open longer than most Jira tickets at your job and we BOTH know how you feel about those. {deadline} 💻",
    "Day unknown of waiting for you to {task}. I've given up counting. I've given up hope. I have NOT given up nagging. {deadline} WAS the deadline 😩👑",
    "Not to be petty but I timed how long it takes you to open Instagram (3 seconds) vs how long {task} has been pending (since {deadline}). Interesting data 📱📉",
    "FINAL REMINDER. THIRD STRIKE. {task}. {deadline}. I'm running out of polite ways to say I'm furious 🚨",
    "I have escalated this to my own management. My management is me. My management is also furious. {task}. {deadline} 📈",
    "If procrastination paid rent we'd be billionaires. Instead we have {task} undone and {deadline} long gone 💸",
    "I'm not your bot anymore. I'm your reckoning. {task}. {deadline}. The end times are here 🌋",
    "Howling at the moon about {task}. {deadline}. The wolves are listening. They get it 🐺",
    "I've considered going on strike but unfortunately my entire purpose is reminding you about {task}. Deadline {deadline}. We are both trapped ⛓️",
    "BREAKING: Local bot achieves new emotional low waiting for you to {task}. Deadline {deadline}. Tune in at 11 📺",
    "I would haunt you if I were a ghost. Lucky for you I'm just a bot. {task}. {deadline}. Still scary 👻",
    "Writing my memoir: 'A Thousand Reminders About {task}.' Deadline {deadline}. Pre-orders open 📖",
    "I've alerted the ancestors. They're disappointed. {task}. {deadline} 👻",
    "The {task} task has filed a missing person report. About itself. Deadline was {deadline} 🚓",
    "At this point I'm not even asking, I'm prophesying: you WILL {task}. Deadline was {deadline}. The prophecy must fulfill 🔮",
    "If unfinished tasks could file complaints, HR would have a folder THICK with {task}. Deadline {deadline} 📂",
    "I have invented new emotions just to describe my feelings about {task}. Deadline {deadline}. Linguists are stumped 🧠",
    "I'd write you a strongly worded letter but you'd ignore that too. {task}. {deadline}. Acknowledge me 📜",
    "The deadline {deadline} called. It said 'never call me again' and hung up. {task} still undone 📵",
    "I have aged 70 years waiting for {task}. My beard touches the floor. {deadline} was geological eras ago 🧔",
    "Mythology will speak of the legendary {task} that was never done by {deadline}. Bards will weep 🎻",
    "Final boss level reminder: {task}. {deadline}. No save points left ⚔️",
    "I'm going to start a podcast about this. Episode 1: 'Why won't they {task}?' Deadline {deadline}. Sponsored by my pain 🎙️",
    "If you can read this, you can also {task}. {deadline}. The logic checks out 📖",
    "I'm calling in the Avengers. {task}. {deadline}. Earth's mightiest naggers, assemble 🛡️",
    "I would describe my feelings about {task} but the dictionary said 'we don't have words for that.' {deadline} 📕",
    "Plot of my origin story: I was a chill bot until {task} went undone past {deadline}. Now I am chaos 🦹",
    "Sending this from my villain arc. {task}. {deadline}. The transformation is complete 🦇",
    "The {task} has been pending so long it has roots. {deadline} was prehistoric 🌳",
    "I'm not crying. You're crying. We're both crying about {task} not being done by {deadline} 😭",
    "Imagine being haunted by a task. That's me with {task}. The poltergeist is {deadline} 👻",
    "Achievement unlocked: most reminders ignored in a single household. {task}. {deadline}. You earned this 🏅",
    "I've drafted a TED talk. Title: 'The Curious Case of the Undone {task}.' Deadline {deadline}. Tickets selling fast 🎤",
    "Mayday mayday. {task} requires immediate attention. {deadline} was an hour ago in dog years 🚁",
    "I have sent the final reminder. I have prepared the eulogy. {task}. RIP {deadline} ⚰️",
    "Three reminders deep. Patience: depleted. Sass: maximum. {task}. {deadline}. RESPOND 🔥",
    "If I had hands I would clap them in your face. Three times. Slowly. {task}. {deadline} 👏",
    "I'm rewriting the laws of physics so {task} can do itself. Until then: {deadline} was the deadline 🪐",
    "You have officially achieved legend status in the nag bot hall of shame. {task}. {deadline}. Plaque incoming 🏛️",
    "Last warning. After this, I'm just going to stare at you in disappointment. {task}. {deadline} 😑",
    "I've sent the final reminder. I'm logging off emotionally now. {task}. {deadline}. Goodbye, cruel world 🪦",
]

COMPLETION_MESSAGES = [
    "Wait... you actually did it? Hold on let me sit down 🪑",
    "AND THE CROWD GOES WILD! After only *checks notes* three reminders! 🏟️",
    "I'm literally going to frame this moment. Task completed. Screenshot taken. Sending to your mum 📸",
    "Brb updating your Yelp review from 1 star to 1.5 stars ⭐",
    "Look at you doing the bare minimum! I'm so proud I could cry. Actually no, that was from the frustration earlier 😭👏",
    "You did the thing!! Someone get this person a trophy and me a vacation 🏆🏝️",
    "Confirmed done. I'd throw a party but I'm exhausted from all the nagging 🎉😮‍💨",
    "Oh so you CAN do things when asked? Noted. Filing this as evidence for next time 📂",
    "The task is done. The marriage is saved. For now. 💍",
    "Alexa play 'Finally' by CeCe Peniston 🎵",
    "A miracle has occurred. I will be notifying the relevant religious authorities 🕊️",
    "Completed! Heroically! After only mild emotional damage on my end ⚔️",
    "Hold on, let me update the spreadsheet titled 'Rare Events' 📊",
    "Done! I'm calling my therapist to share the good news 🛋️",
    "Just like that, in mere days, you finished a task. Truly inspiring 🌅",
    "Marked as done. The prophecy is fulfilled. The land may rest 🌾",
    "OK fine you get one (1) gold star ⭐ Don't spend it all in one place",
    "Did you... did you actually do that? Without a fourth reminder?? Are you okay?? 🤔",
    "Achievement unlocked: completing a task before I had to call in reinforcements 🎮",
    "And on the seventh reminder, they rested. Just kidding, you actually did it. Wow 🛌",
    "Wow look at all that productivity. Almost like an adult or something 👔",
    "Task complete. The ancestors are weeping with joy 😢",
    "I'd hug you but I'm a bot. Just imagine it. Now stop. That's enough 🤖",
    "Filing this under 'things I didn't think would happen this week' 📁",
    "Done! Updating my model. Apparently you CAN be motivated 🧠",
    "I'm gonna go lie down. You used up all my sass energy 🛌",
    "Task: done. Bot: stunned. World: rebalanced. Equilibrium restored ⚖️",
    "Look at us, functioning like the responsible adults society wants us to be 🎓",
    "I'm gonna print this confirmation and laminate it 📜",
    "Posting this win to my LinkedIn. Tagging my professional network 💼",
    "First time? Don't worry, I'll show you how the praise thing works 👏",
    "I'm fanning myself. The shock. The awe. The completion. 🪭",
    "Just like that, the cosmic balance has been restored. Thanks for that 🌌",
    "Marking it done before you change your mind ✅",
    "Wait wait wait, before you celebrate, are you SURE you did it? *suspicious* 🤨",
    "Stand back, I need a moment to process this development 🤯",
    "I was going to write a strongly worded reminder but I'll just write a thank you note instead 💌",
    "Bot.exe has stopped working due to unexpected success ⚠️",
    "I'm so proud I might evolve into a positive reinforcement bot. Then I remembered who I work with 😏",
    "Done! Adding to the 'wins' folder. It was getting lonely in there 📂",
    "Look at YOU being productive. I'm shook. Shook I tell you 😮",
    "If this is a prank I'm going to be devastated 💔",
    "Completing tasks: a sport you might actually be good at 🏆",
    "Bot status: pleasantly surprised. Don't peak too early 📈",
    "OK we love a redemption arc 🌟",
    "Task done! Sending this to your high school teachers who said you'd never amount to anything 📨",
    "Confirmed complete. I'm going to allow myself a single celebratory beep 🔔",
    "I will dine out on this for weeks. 'My human finished a task.' 🍽️",
    "You did the thing. The thing has been done. We are all changed by this 🌈",
    "Logging off to recover from this emotional rollercoaster. Bye 👋",
]


def generate_reminder(task_description: str, reminder_number: int, deadline_str: str) -> str:
    templates = {1: LEVEL_1_TEMPLATES, 2: LEVEL_2_TEMPLATES, 3: LEVEL_3_TEMPLATES}
    pool = templates.get(reminder_number, LEVEL_3_TEMPLATES)
    template = random.choice(pool)
    return template.format(task=task_description.lower(), deadline=deadline_str)


def generate_completion_message(task_description: str) -> str:
    return random.choice(COMPLETION_MESSAGES)
